spring.application.name=veterinaria

# Conexión a Base de Datos Local
spring.datasource.url=jdbc:mysql://localhost:3306/veterinaria?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=admin

# Conexión a Railway (Comentada en caso de que la necesites después)
# spring.datasource.url=jdbc:mysql://${MYSQLHOST:nozomi.proxy.rlwy.net}:${MYSQLPORT:39709}/${MYSQLDATABASE:railway}
# spring.datasource.username=${MYSQLUSER:root}
# spring.datasource.password=${MYSQLPASSWORD:SyDvBfryarvXIwvXQhjxPMTgQGBpXXWb}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=${PORT:8080}