spring.application.name=veterinaria

# Configuración Dinámica (Inteligente)
spring.datasource.url=jdbc:mysql://${MYSQLHOST:nozomi.proxy.rlwy.net}:${MYSQLPORT:39709}/${MYSQLDATABASE:railway}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:SyDvBfryarvXIwvXQhjxPMTgQGBpXXWb}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate - Crea las tablas automáticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Puerto para Railway
server.port=${PORT:8080}